[build]
target = "x86_64-pc-windows-gnullvm"

[target.x86_64-pc-windows-gnullvm]
linker = "C:/Users/ddean/modtools/llvm-mingw-20260922-ucrt-x86_64/bin/x86_64-w64-mingw32-clang.exe"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static"]
