"""Generate mod/src/frames_gen.rs from sheets/frames.json.

Each row of the frames sheet becomes one `Frame` struct in the DLL, so the numbers in the sheet are the
numbers the game runs. The movement columns come from the real AC6 params (tools/ac6_numbers.py).
Run before building the DLL.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
rows = json.load(open(os.path.join(HERE, "..", "sheets", "frames.json"), encoding="utf-8"))["rows"]
sysrows = {r["id"]: r for r in json.load(open(os.path.join(HERE, "..", "sheets", "systems.json"), encoding="utf-8"))["rows"]}

WSTATS = json.load(open(os.path.join(HERE, "..", "sheets", "weapon_stats.json"), encoding="utf-8"))
WROWS = json.load(open(os.path.join(HERE, "..", "sheets", "weapons.json"), encoding="utf-8"))["rows"]
SYSW = sysrows["sys_weapons"]
BULLET_ID0 = 99910000
GUN_INDEX = {w["id"]: i for i, w in enumerate([w for w in WROWS if w["kind"] in ("ranged", "back") and w["id"] in WSTATS])}

INT_FIELDS = ["gun_bullet_id", "gun_bullet_charged_id", "gun_total_rounds", "gun_charged_rounds", "back_bullet_id", "back_total_rounds"]
GUN_FIELDS = ["gun_cooldown_s", "gun_charge_s", "back_cooldown_s"]

FIELDS = [
    "qb_en_pct", "qb_cooldown_s", "qb_duration_s", "qb_distance_m",
    "boost_en_pct_per_s", "vboost_en_pct_per_s",
    "en_regen_pct_per_s", "en_regen_delay_s", "en_empty_delay_s", "en_empty_restore_pct",
    "ground_boost_mps", "ground_boost_accel", "air_boost_mps", "air_boost_accel",
    "ground_brake_mps2", "landing_brake_mps2",
    "vboost_up_mps", "vboost_up_accel", "vboost_h_mps", "vboost_h_accel",
    "air_h_mps", "air_h_accel", "fly_h_brake_mps2", "fly_up_brake_mps2",
    "gravity_mps2", "fall_max_mps", "move_speed_scale",
]

out = ["// GENERATED by tools/gen_frames_rs.py from sheets/frames.json and sheets/systems.json. Do not edit by hand.", "",
       "pub struct Frame {", "    pub id: &'static str,", "    pub class_row: i32,"]
out += [f"    pub {k}: f32," for k in FIELDS + GUN_FIELDS]
out += [f"    pub {k}: i32," for k in INT_FIELDS]
out += ["}", "",
        f"pub const SIZE_SCALE: f32 = {float(sysrows['sys_size']['size_scale'])!r};",
        f"pub const AIM_HEIGHT_M: f32 = {float(SYSW['aim_height_m'])!r};",
        f"pub const MUZZLE_FORWARD_M: f32 = {float(SYSW['muzzle_forward_m'])!r};",
        f"pub const LUNGE_MPS: f32 = {float(SYSW['blade_lunge_mps'])!r};",
        f"pub const LUNGE_S: f32 = {float(SYSW['blade_lunge_s'])!r};",
        f"pub const DEBUG_SFX_COUNT: i32 = {len(SYSW.get('debug_sfx', []))};", "",
        f"pub const FRAMES: [Frame; {len(rows)}] = ["]
for r in rows:
    out.append("    Frame {")
    out.append(f"        id: {json.dumps(r['id'])},")
    out.append(f"        class_row: {int(r['class_row'])},")
    for k in FIELDS:
        out.append(f"        {k}: {float(r[k])!r},")
    gun = r["start_weapon_right"]
    gi = GUN_INDEX[gun]
    st = WSTATS[gun]["attacks"]
    nrm, chg = st["normal"], st.get("charged", st["normal"])
    back = r.get("start_weapon_back")
    bst = WSTATS[back] if back else None
    vals = dict(gun_cooldown_s=nrm["reload_s"], gun_charge_s=max(chg["charge_s"], 0.3),
                back_cooldown_s=(bst["attacks"]["normal"]["reload_s"] if bst else 1.0))
    for k, v in vals.items():
        out.append(f"        {k}: {float(v)!r},")
    ints = dict(gun_bullet_id=BULLET_ID0 + gi * 10, gun_bullet_charged_id=BULLET_ID0 + gi * 10 + 1,
                gun_total_rounds=int(WSTATS[gun]["total_rounds"]), gun_charged_rounds=int(chg["rounds"]),
                back_bullet_id=(BULLET_ID0 + GUN_INDEX[back] * 10 if back else 0), back_total_rounds=(int(bst["total_rounds"]) if bst else 0))
    for k, v in ints.items():
        out.append(f"        {k}: {v},")
    out.append("    },")
out.append("];")
path = os.path.join(HERE, "..", "mod", "src", "frames_gen.rs")
open(path, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote", os.path.normpath(path), len(rows), "frames")
